---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

env:
  - ANSIBLE_VERSION=1.8 SLAPD_DOMAIN=
    SLAPD_PASSWORD='pass'
    SLAPD_DOMAIN='domain.local'
    SLAPD_ORGANIZATION='My Org, Inc.'

  - ANSIBLE_VERSION=2.0
    SLAPD_PASSWORD='pass'
    SLAPD_DOMAIN='domain.local'
    SLAPD_ORGANIZATION='My Org, Inc.'

  - ANSIBLE_VERSION=2.2
    SLAPD_PASSWORD='pass'
    SLAPD_DOMAIN='domain.local'
    SLAPD_ORGANIZATION='My Org, Inc.'

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install: []

install:
  # Install ansible
  - pip install ansible
  - pip install ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - ln -sf tests/ansible.cfg ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint tests/test.yml
  - ansible-playbook tests/test.yml -i tests/inventory


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
