---

- name: Configure debconf
  debconf:
    name: "{{ ldap_package }}"
    question: "{{ item.question }}"
    vtype: "{{ item.vtype }}"
    value: "{{ item.value }}"
  with_items:
    - { "question": "{{ ldap_package }}/backend", "vtype": "select", value: "HDB" }
    - { "question": "{{ ldap_package }}/domain", "vtype": "text", value: "{{ ldap_domain }}" }
    - { "question": "shared/organization", "vtype": "text", value: "{{ ldap_organization }}" }
  changed_when: false

- name: Install OpenLDAP package
  apt:
    name: '{{ ldap_package }}'
    state: present
    install_recommends: no

- name: Test
  debug: var=item
  with_items: test_items
